#+TITLE:  org-abntex2
#+AUTHOR: Lucas Vieira
#+EMAIL:  lucasvieira@protonmail.com

* Introdução

Este é um modelo para escrever artigos sob as normas da ABNT,
utilizando Org Mode. Trata-se de um /template/, provido para que o
acadêmico possa simplesmente copiar os arquivos de interesse e
modificá-los segundo sua necessidade.

O foco primário é garantir compatibilidade com o modelo dos trabalhos
da Universidade Federal dos Vales do Jequitinhonha e do Mucuri, uma
vez que sou discente desta instituição. Dito isto, enquanto estiver
nela, manterei este /template/, uma vez que me serve.

* Motivação

Este projeto tem uma forte motivação pessoal, vinda do meu viés para
com ferramentas abertas, como Emacs e Org Mode. O formato Org já me
acompanha há alguns meses, e faço absolutamente tudo com ele. Todavia,
ainda faltava uma ferramenta que tornasse possível reduzir o
/boilerplate/ da linguagem TeX para meu proveito acadêmico,
possibilitando-me criar trabalhos sob as normas da ABNT e das
convenções da minha universidade. /org-abntex2/ é minha tentativa de
perseguir esta necessidade, com um /template/ mínimo que pudesse ser
reusado e readaptado para outras situações.

* Modo de uso

O uso do projeto está exemplificado no arquivo /main.org/ e em sua
versão em PDF, /main.pdf/, inclusos neste repositório. Uma leitura e
observação cuidadosa de ambos os arquivos revelará a forma como este
/template/ funciona.

Caso haja algum problema, você poderá criar uma /issue/ neste repositório.

** Dependências

Para rodar o projeto com sucesso. é necessária uma distribuição LaTeX de sua
preferência. Recomendo [[https://www.texstudio.org/#download][TeXStudio]] para Linux, preferencialmente atualizada.

*** Usando DOOM EMACS

Todo o projeto foi feito e configurado usando a distribuição [[https://github.com/doomemacs/doomemacs][DOOM EMACS]], então
certas configurações nativas ao DOOM são presumidas ao utilizar esse template.

Após instalar DOOM, dentro do arquivo de configuração =init.el= é necessário
habilitar os módulos:

#+begin_src emacs-lisp
       :lang
       latex             ; writing papers in Emacs has never been so fun
       org               ; organize your plain life in plain text

       :completion
       vertico           ; the search engine of the future
#+end_src

Isso habilitará org-mode, AUCTeX para edição mais fácil e prática de LaTeX, e o
pacote de bibliografias [[https://github.com/emacs-citar/citar][citar]].

Com isso a configuração deve estar completa, mas se não quiser utilizar DOOM
EMACS, é possível configurar o seu ambiente manualmente.

*** Manualmente

Você vai precisar das seguintes extensões para Emacs:

- =org=, preferencialmente na versão *mais nova*, que pode ser instalada
  pelo repositório oficial, como indicado no site da ferramenta;
- =org-ref=, extensão para gerenciamento de bibliografia em Org Mode.

ou

- =citar=, que faz a mesma coisa de uma forma diferente.

Opcionalmente, você poderá utilizar:

- =AUCTeX=, que provê ferramentas para edição de arquivos TeX no Emacs.

* Licenciamento

Este projeto é licenciado sob a licença BSD 2-Clause "Simplified". Veja o
arquivo /LICENSE/ e os arquivos /main.{org,pdf}/ para mais detalhes.
